### ISSUE TITLE
All members double

### ISSUE THREAD

**Issue by rienJa** [carambolecomputer/issue-tracker#3]
Hi,
If  I select KNBB Nijmegen  3 banden B2 all members are double in the list.

Best regards,
Rien

**Comment by rvgate** [comment]
This is intentional as the amount may vary based on if its an a "dubbelpartij" or not. In biljartpoint this is defined as the columns Tecar and Dpcar.

Since there is no difference for the biljartcomputer, the only way to get these values during export is to add the same player twice with different amount values.

**Comment by rvgate** [comment]
Additonallly, if the player is playing for multiple teams within the same competition, you will get different entries for each team for this player as well.
